loopback:
  build: .
  expose:
    - "80"
    - "443"
    - "28015"
    - "29015"
  ports:
    - 3000:3000
  links:
    - mongodb
  environment:
    VIRTUAL_HOST: api.company.com
    VIRTUAL_PORT: 3000
    LETSENCRYPT_EMAIL: user@company.com
    LETSENCRYPT_HOST: api.company.com

mongodb:
  build: ./MongoDB
  ports:
    - "27017:27017"
    - "27018:27018"
    - "27019:27019"
    - "28017:28017"
